### ISSUE TITLE
the social icons at the bottom don't work

### ISSUE THREAD

**Issue by chepe263** [farm-fe/farm-fe.github.io#131]
![Screenshot 2024-07-17 at 6 46 43 PM](https://github.com/user-attachments/assets/9232cf3a-cfe7-4a5a-86a0-ddd013f7760c)

The social icons at the bottom are not wrapped in a link `<a />`

Could somebody add urls for twitter/x and discord?

Also, is there a svg for X (formerly twitter)?

**Comment by wre232114** [comment]
We'll add it
