### ISSUE TITLE
Remove the Glowing strips in Documentation

### ISSUE THREAD

**Issue by dulranga** [farm-fe/farm-fe.github.io#137]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/40ba3ac1-5b68-45de-959d-68632d97c30f">

---
these diagonal strips make the documentation harder to read. 
Even though its a nice touch for the site, it distracts users from reading the docs. Especially when scrolling.

**Comment by ErKeLost** [comment]
Thanks for the feedback. The background color has been removed. Thank you for using farm.

**Comment by dulranga** [comment]
I think it crashed the website 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c5f2dfd4-2c40-4543-b45a-d586bb32c490">

**Comment by ErKeLost** [comment]
I just tried to fix this problem. You can try it again

**Comment by dulranga** [comment]
I've requested access to the deployment preview to see if it works :)
