### ISSUE TITLE
Not Mobile Optimsed

### ISSUE THREAD

**Issue by n-ce** [farm-fe/farm-fe.github.io#138]
There is a night and day difference the vite website and farm website where vitepress is very light on resources. I just wanted to see how to host a farm application on github actions but I am unable to do so.
![Screenshot_20240822-131508](https://github.com/user-attachments/assets/22081bfe-a517-488b-86af-177724b160b2)
It's stuck here, while the waves in background move at around 0.3fps.

**Comment by ErKeLost** [comment]
Thank you for your feedback, the mobile version of siderbar has been fixed Thank you for using farm

**Comment by ErKeLost** [comment]
fixed
